name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers workflow on push to the 'main' branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # You can change the version if needed

      - name: Install dependencies (if any)
        run: npm install

      - name: Run tests (if any)
        run: npm test  # Skip this if you don't have tests

      - name: Build Project (if necessary)
        run: npm run build  # Skip if you don't have a build step

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Where your index.html is located
