# Workflow for deploying a static site to Vercel
name: Deploy to Vercel

on:
    # Runs on pushes to the main branch
    push:
        branches: ["main"]

    # Allows manual runs from the Actions tab
    workflow_dispatch:

# Permissions for the GitHub Actions token
permissions:
    contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16" # Specify the Node version compatible with your project

            - name: Install Vercel CLI
              run: npm install -g vercel

            - name: Deploy to Vercel
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} # Using the token stored in GitHub Secrets
              run: vercel --prod --token=$VERCEL_TOKEN
